In [60]:
import pandas as pd
housing = pd.read_csv('muabannha_clean.csv')
#housing.head()

In [61]:
import numpy as np
house = np.array(housing)
loaiNha = np.zeros([3278, 1])
house = np.hstack([house, loaiNha])
house.shape, house[0]

((3278, 58),
 array([3.3, 34.0, 737669.0, 737714.0, 5.0, 4.0, 3.0, 0, 21.0083647,
        105.8180219, False, False, True, True, False, False, False, False,
        False, False, True, True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], dtype=object))

In [62]:
for i in range(3278):
    for j in range(38, 58):
        house[i][57] += 1
        if house[i][j] == 1:
            if house[i][j] == 14:
                house[i][j] += 138
            elif house[i][j] == 16:
                house[i][j] += 88            
            break
            
for i in range(19):
    house = np.delete(house, 38, 1)
house.shape, house[0]

((3278, 39),
 array([3.3, 34.0, 737669.0, 737714.0, 5.0, 4.0, 3.0, 0, 21.0083647,
        105.8180219, False, False, True, True, False, False, False, False,
        False, False, True, True, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, 16.0], dtype=object))

In [63]:
tienIch = np.zeros([3278, 1])
house = np.hstack([house, tienIch])

for i in range(3278):
    for j in range(10, 38):
        if house[i][j] == True:
            val = 1
        else:
            val = 0
        house[i][39] += val*(2**(j - 10))
            
for i in range(28):
    house = np.delete(house, 10, 1)

house.shape, house[0]

((3278, 12),
 array([3.3, 34.0, 737669.0, 737714.0, 5.0, 4.0, 3.0, 0, 21.0083647,
        105.8180219, 16.0, 3084.0], dtype=object))

In [64]:
house.shape

(3278, 12)

In [65]:
dienTichvaTang = np.zeros([3278, 1])
house = np.hstack([house, dienTichvaTang])

In [66]:
import math
for i in range(3278):
    house[i][12] += (16*math.log2(house[i][1])+math.log2(house[i][4]))

In [67]:
house[0]

array([3.3, 34.0, 737669.0, 737714.0, 5.0, 4.0, 3.0, 0, 21.0083647,
       105.8180219, 16.0, 3084.0, 83.7213335548928], dtype=object)

In [68]:
caoCap = np.zeros([3278, 1])
house = np.hstack([house, caoCap])

for i in range(3278):
    if house[i][10] == 13:
        house[i][-1] -= 12
    elif house[i][10] == 4:
        house[i][-1] -= 15
    elif house[i][10] == 10:
        house[i][-1] -= 10
    elif house[i][10] == 14:
        house[i][-1] -= 9
    elif house[i][10] == 7:
        house[i][-1] -= 8
    elif house[i][10] == 1:
        house[i][-1] -= 7
    elif house[i][10] == 11:
        house[i][-1] -= 6
    elif house[i][10] == 6: #2120
        house[i][-1] -= 5
    elif house[i][10] == 13:
        house[i][-1] += 3
    elif house[i][10] == 19:
        house[i][-1] += 2
    elif house[i][10] in (5,12):
        house[i][-1] += 1
    elif house[i][10] == 20:
        house[i][-1] += 0
    elif house[i][10] in (2,15):
        house[i][-1] -= 1
    elif house[i][10] == 18:
        house[i][-1] -= 2
    elif house[i][10] in (8,9):
        house[i][-1] -= 3
    
    elif house[i][10] == 16:
        house[i][-1] -= 23
#    elif house[i][10] == 17:
#        house[i][-1] -= 7
#    elif house[i][10] == 18:
#        house[i][-1] -= 3
#    elif house[i][10] == 19:
#        house[i][-1] -= 5
    else:
        house[i][-1] -= 4

In [69]:
house = np.delete(house, 10, 1)

In [70]:
y = house[:,0]

for i in range(3278):
    y[i] = math.log2(y[i])

X = np.delete(house, 0, 1)

In [71]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=22)

In [72]:
from sklearn.metrics import mean_squared_error
from sklearn.neighbors import KNeighborsRegressor as kNN
neigh = kNN(n_neighbors=8)
neigh.fit(X_train, y_train)
y_predict = neigh.predict(X_test)

for i in range(y_test.size):
    y_test[i] = 2**y_test[i]
    y_predict[i] = 2**y_predict[i]

var = 0
for i in range(y_predict.size):
    var = var+abs(y_test[i]-y_predict[i])
    #print(y_test[i]-predict)
print("Sai so trung binh:", var/y_predict.size)

knn_mse = mean_squared_error(y_test, y_predict)
knn_rmse = np.sqrt(knn_mse)
knn_rmse

Sai so trung binh: 3.9746396638129426


10.104648491706016

In [41]:
from sklearn.tree import DecisionTreeRegressor
dt = DecisionTreeRegressor()
dt.fit(X_train, y_train)
y_predict = dt.predict(X_test)

var = 0
for i in range(y_predict.size):
    var = var+abs(y_test[i]-y_predict[i])
    #print(y_test[i]-predict)
print(var/y_predict.size)

tree_mse = mean_squared_error(y_test, y_predict)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

0.8272317921998616


1.5274503771578374

In [17]:
from sklearn.linear_model import LinearRegression
lir = LinearRegression()
lir.fit(X_train, y_train)

var = 0
for i in range(y_predict.size):
    var = var+abs(y_test[i]-y_predict[i])
    #print(y_test[i]-predict)
print(var/y_predict.size)

y_predict = lir.predict(X_test)
lin_mse = mean_squared_error(y_test, y_predict)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

10.220238414634148


12.219147293071213

In [18]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)
#print(forest_rmse)
#print(display_scores(forest_rmse_scores))

RandomForestRegressor()

In [19]:
y_pred = rf.predict(X_test)

In [20]:
var = 0
for i in range(y_pred.size):
    var = var+abs(y_test[i]-y_pred[i])
    #print(y_test[i]-predict)
print(var/y_predict.size)

tree_mse = mean_squared_error(y_test, y_predict)
tree_rmse = np.sqrt(tree_mse)
tree_rmse

8.966281605060978


12.219147293071213

In [ ]:
nha1 = 0
nha2 = 0
nha3 = 0
nha4 = 0
nha5 = 0
nha6 = 0
nha7 = 0
nha8 = 0
nha9 = 0
nha10 = 0
nha11 = 0
nha12 = 0
nha13 = 0
nha14 = 0
nha15 = 0
nha16 = 0
nha17 = 0
nha18 = 0
nha19 = 0
nha20 = 0
for i in range(3278):
    if house[i][0] < 10.056562:
        if house[i][-1] == 1:
            nha1 += 1
        elif house[i][-1] == 2:
            nha2 += 1
        elif house[i][-1] == 3:
            nha3 += 1
        elif house[i][-1] == 4:
            nha4 += 1
        elif house[i][-1] == 5:
            nha5 += 1
        elif house[i][-1] == 6:
            nha6 += 1
        elif house[i][-1] == 7:
            nha7 += 1
        elif house[i][-1] == 8:
            nha8 += 1
        elif house[i][-1] == 9:
            nha9 += 1
        elif house[i][-1] == 10:
            nha10 += 1
        elif house[i][-1] == 11:
            nha11 += 11
        elif house[i][-1] == 12:
            nha12 += 1
        elif house[i][-1] == 13:
            nha13 += 1
        elif house[i][-1] == 14:
            nha14 += 1
        elif house[i][-1] == 15:
            nha15 += 1
        elif house[i][-1] == 16:
            nha16 += 1
        elif house[i][-1] == 17:
            nha17 += 1
        elif house[i][-1] == 18:
            nha18 += 1
        elif house[i][-1] == 19:
            nha19 += 1
        elif house[i][-1] == 20:
            nha20 += 1
nha1,nha2,nha3,nha4,nha5,nha6,nha7,nha8,nha9,nha10,nha11,nha12,nha13,nha14,nha15,nha16,nha17,nha18,nha19,nha20